[project]
name = "py-tools"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pillow>=12.3.0",
]

[project.scripts]
py-tools = "py-tools:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
